from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1169, 639)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.Signal_graphicsView = PlotWidget(self.layoutWidget)
        self.Signal_graphicsView.setObjectName("Signal_graphicsView")
        self.verticalLayout.addWidget(self.Signal_graphicsView)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.no_chunks_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.no_chunks_label.setFont(font)
        self.no_chunks_label.setObjectName("no_chunks_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.no_chunks_label)
        self.fitting_order_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fitting_order_label.setFont(font)
        self.fitting_order_label.setObjectName("fitting_order_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fitting_order_label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sig_clip_Slider = QtWidgets.QSlider(self.layoutWidget)
        self.sig_clip_Slider.setEnabled(False)
        self.sig_clip_Slider.setMinimum(40)
        self.sig_clip_Slider.setMaximum(90)
        self.sig_clip_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.sig_clip_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sig_clip_Slider.setObjectName("sig_clip_Slider")
        self.horizontalLayout_6.addWidget(self.sig_clip_Slider)
        self.clipp_val_label = QtWidgets.QLabel(self.layoutWidget)
        self.clipp_val_label.setObjectName("clipp_val_label")
        self.horizontalLayout_6.addWidget(self.clipp_val_label)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fitting_order_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.fitting_order_SpinBox.setObjectName("fitting_order_SpinBox")
        self.horizontalLayout_7.addWidget(self.fitting_order_SpinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.no_chunks_SpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.no_chunks_SpinBox.setObjectName("no_chunks_SpinBox")
        self.horizontalLayout_8.addWidget(self.no_chunks_SpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.enable_extrapol_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.enable_extrapol_checkBox.setFont(font)
        self.enable_extrapol_checkBox.setObjectName("enable_extrapol_checkBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.enable_extrapol_checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.sig_clip_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sig_clip_label.setFont(font)
        self.sig_clip_label.setObjectName("sig_clip_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sig_clip_label)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.error_map_graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.error_map_graphicsView.setObjectName("error_map_graphicsView")
        self.gridLayout.addWidget(self.error_map_graphicsView, 0, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontal_axis_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.horizontal_axis_label.setFont(font)
        self.horizontal_axis_label.setObjectName("horizontal_axis_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.horizontal_axis_label)
        self.vertical_axis_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vertical_axis_label.setFont(font)
        self.vertical_axis_label.setObjectName("vertical_axis_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.vertical_axis_label)
        self.constant_value_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.constant_value_label.setFont(font)
        self.constant_value_label.setObjectName("constant_value_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.constant_value_label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.constant_value_Slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.constant_value_Slider.setMaximum(25)
        self.constant_value_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.constant_value_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.constant_value_Slider.setObjectName("constant_value_Slider")
        self.horizontalLayout_9.addWidget(self.constant_value_Slider)
        self.const_slider_val_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.const_slider_val_label.setObjectName("const_slider_val_label")
        self.horizontalLayout_9.addWidget(self.const_slider_val_label)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.vertical_axis_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.vertical_axis_comboBox.setEnabled(False)
        self.vertical_axis_comboBox.setObjectName("vertical_axis_comboBox")
        self.horizontalLayout_10.addWidget(self.vertical_axis_comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 2)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontal_axis_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.horizontal_axis_comboBox.setObjectName("horizontal_axis_comboBox")
        self.horizontal_axis_comboBox.addItem("")
        self.horizontal_axis_comboBox.addItem("")
        self.horizontal_axis_comboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.horizontal_axis_comboBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.gridLayout.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.error_map_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.error_map_Button.setObjectName("error_map_Button")
        self.horizontalLayout.addWidget(self.error_map_Button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 3)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1169, 26))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSignal = QtWidgets.QAction(MainWindow)
        self.actionSignal.setObjectName("actionSignal")
        self.menuOpen.addAction(self.actionSignal)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_row_equation(self, lenth, chunk_no, equation, error):
        self.tableWidget.setRowCount(lenth)
        self.tableWidget.setItem(chunk_no, 0, QTableWidgetItem(str(1 + chunk_no)))
        self.tableWidget.setItem(chunk_no, 1, QTableWidgetItem(equation))
        self.tableWidget.setItem(chunk_no, 2, QTableWidgetItem(error))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signal Fitting"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Chunk Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fitted Equation"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Error"))
        self.no_chunks_label.setText(_translate("MainWindow", "Number of Chunks"))
        self.fitting_order_label.setText(_translate("MainWindow", "Fitting Order"))
        self.clipp_val_label.setText(_translate("MainWindow", "%"))
        self.enable_extrapol_checkBox.setText(_translate("MainWindow", "Enable Extrapolation"))
        self.sig_clip_label.setText(_translate("MainWindow", "Signal Clipping"))
        self.horizontal_axis_label.setText(_translate("MainWindow", "Horizontal Axis"))
        self.vertical_axis_label.setText(_translate("MainWindow", "Vertical Axis"))
        self.constant_value_label.setText(_translate("MainWindow", "Overlab"))
        self.const_slider_val_label.setText(_translate("MainWindow", "Value"))
        self.horizontal_axis_comboBox.setItemText(0, _translate("MainWindow", "Number of Chunks"))
        self.horizontal_axis_comboBox.setItemText(1, _translate("MainWindow", "Order"))
        self.horizontal_axis_comboBox.setItemText(2, _translate("MainWindow", "Overlap Percentage"))
        self.error_map_Button.setText(_translate("MainWindow", "Create"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.actionSignal.setText(_translate("MainWindow", "Signal"))


from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
